trigger:
  branches:
    include:
      - '*'
pr: none

pool:
  vmImage: ubuntu-latest 

resources:
  repositories:
    # Adicionando repositório de templates base para o processo de cicd
    - repository: templates
      type: github
      name: leoviana00/azure-templates-pipeline
      ref: 'refs/heads/main'
      endpoint: 'leoviana00'

    # Adicionando repositório de templates base para helm charts
    - repository: helmrepo
      type: github
      name: leoviana00/azure-template-helm-chart
      ref: 'refs/heads/master'
      endpoint: 'leoviana00'

variables:
  - group: acr-variable-group
  - template: templates/node/ci-vars-template.yml@templates
    parameters:
      projectName: node-pipeline-azure-devops
      dockerRegistryServiceConnectionName: acr-connection-aks
      dockerfile: '$(projectName)/Dockerfile'
      buildContext: '$(Build.SourcesDirectory)'
      chartHelmFile: 'azure-template-helm-chart/templates/node/$(projectName)'

steps: 
  - checkout: self
  - checkout: helmrepo 
  - template: templates/node/ci-steps-template.yml@templates
  
 